Airport.create!(city: "Ft. Lauderdale", state: "FL", code: "FLL")
Airport.create!(city: "Palm Beach", state: "FL", code: "PBI")
Airport.create!(city: "Miami", state: "FL", code: "MIA")
Airport.create!(city: "New York", state: "NY", code: "JFK")
Airport.create!(city: "Boston", state: "MA", code: "BOS")